<?php

namespace Database\Seeders;

use App\Models\Party;
use Illuminate\Database\Seeder;

class PartySeeder extends Seeder
{
    public $parties = [
        [
            'id' => 1,
            'name' => 'John Smith',
            'phone' => '0412345678',
            'email' => 'john.smith@example.com',
            'tax_number' => '123124567890',
            'country' => 'United States',
            'city' => 'New York',
            'postal_code' => '10001',
            'address' => '123 Main St',
            'billing_address' => '456 Billing St',
            'shipping_address' => '789 Shipping St',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 2,
            'name' => 'Jane Johnson',
            'phone' => '0456789123',
            'email' => 'jane.johnson@example.com',
            'tax_number' => '098752654321',
            'country' => 'United Kingdom',
            'city' => 'London',
            'postal_code' => 'SW1A 1AA',
            'address' => '10 Downing St',
            'billing_address' => '1 Billing Rd',
            'shipping_address' => '15 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 3,
            'name' => 'Michael Brown',
            'phone' => '01234567895',
            'email' => 'michael.brown@example.com',
            'tax_number' => '985765432104',
            'country' => 'Canada',
            'city' => 'Toronto',
            'postal_code' => 'M5V 2T6',
            'address' => '789 Yonge St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '123 Shipping Ave',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 4,
            'name' => 'Emily White',
            'phone' => '0456789234',
            'email' => 'emily.white@example.com',
            'tax_number' => '234567890152',
            'country' => 'Australia',
            'city' => 'Melbourne',
            'postal_code' => '3000',
            'address' => '456 Collins St',
            'billing_address' => '123 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 5,
            'name' => 'David Lee',
            'phone' => '0987654321',
            'email' => 'david.lee@example.com',
            'tax_number' => '311098765432',
            'country' => 'United States',
            'city' => 'Los Angeles',
            'postal_code' => '90001',
            'address' => '1234 Elm St',
            'billing_address' => '567 Billing Ave',
            'shipping_address' => '890 Shipping Ave',
            'status' => 'active',
            'isSupplier' => 1,
        ],
        [
            'id' => 6,
            'name' => 'Sophia Taylor',
            'phone' => '0765432109',
            'email' => 'sophia.taylor@example.com',
            'tax_number' => '214209876543',
            'country' => 'United Kingdom',
            'city' => 'Manchester',
            'postal_code' => 'M1 1AG',
            'address' => '567 Market St',
            'billing_address' => '123 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 7,
            'name' => 'James Anderson',
            'phone' => '0212345678',
            'email' => 'james.anderson@example.com',
            'tax_number' => '4323811098765',
            'country' => 'Canada',
            'city' => 'Vancouver',
            'postal_code' => 'V6B 4Y8',
            'address' => '789 Granville St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '123 Shipping Ave',
            'status' => 'active',
            'isSupplier' => 1,
        ],
        [
            'id' => 8,
            'name' => 'Olivia Garcia',
            'phone' => '0456123789',
            'email' => 'olivia.garcia@example.com',
            'tax_number' => '6543210987864',
            'country' => 'Australia',
            'city' => 'Brisbane',
            'postal_code' => '4000',
            'address' => '123 Queen St',
            'billing_address' => '456 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 9,
            'name' => 'Liam Martinez',
            'phone' => '0897654321',
            'email' => 'liam.martinez@example.com',
            'tax_number' => '7409654321098',
            'country' => 'United States',
            'city' => 'Chicago',
            'postal_code' => '60601',
            'address' => '123 State St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '789 Shipping Ave',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 10,
            'name' => 'Ava Robinson',
            'phone' => '0923456389',
            'email' => 'ava.robinson@example.com',
            'tax_number' => '4321098765097',
            'country' => 'United Kingdom',
            'city' => 'Birmingham',
            'postal_code' => 'B1 1BB',
            'address' => '456 Broad St',
            'billing_address' => '123 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 11,
            'name' => 'William Taylor',
            'phone' => '0856423789',
            'email' => 'william.taylor@example.com',
            'tax_number' => '9876543210976',
            'country' => 'United States',
            'city' => 'San Francisco',
            'postal_code' => '94105',
            'address' => '123 Mission St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '789 Shipping Ave',
            'status' => 'active',
            'isSupplier' => 1,
        ],
        [
            'id' => 12,
            'name' => 'Emma Green',
            'phone' => '0312345678',
            'email' => 'emma.green@example.com',
            'tax_number' => '2345678901478',
            'country' => 'Australia',
            'city' => 'Perth',
            'postal_code' => '6000',
            'address' => '456 Murray St',
            'billing_address' => '123 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 13,
            'name' => 'Noah Turner',
            'phone' => '0987612345',
            'email' => 'noah.turner@example.com',
            'tax_number' => '568327654321098',
            'country' => 'Canada',
            'city' => 'Montreal',
            'postal_code' => 'H3B 4L2',
            'address' => '789 Crescent St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '123 Shipping Ave',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 14,
            'name' => 'Isabella Hernandez',
            'phone' => '0423456789',
            'email' => 'isabella.hernandez@example.com',
            'tax_number' => '6543210987985',
            'country' => 'United States',
            'city' => 'Houston',
            'postal_code' => '77002',
            'address' => '123 Main St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '789 Shipping Ave',
            'status' => 'active',
            'isSupplier' => 1,
        ],
        [
            'id' => 15,
            'name' => 'Mia King',
            'phone' => '0321678904',
            'email' => 'mia.king@example.com',
            'tax_number' => '10987654324007',
            'country' => 'United Kingdom',
            'city' => 'Glasgow',
            'postal_code' => 'G1 1RT',
            'address' => '456 Sauchiehall St',
            'billing_address' => '123 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 16,
            'name' => 'Alexander Scott',
            'phone' => '0765234198',
            'email' => 'alexander.scott@example.com',
            'tax_number' => '32109876543755',
            'country' => 'Australia',
            'city' => 'Adelaide',
            'postal_code' => '5000',
            'address' => '123 King William St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '789 Shipping Ave',
            'status' => 'active',
            'isSupplier' => 1,
        ],
        [
            'id' => 17,
            'name' => 'Ella Phillips',
            'phone' => '0867432109',
            'email' => 'ella.phillips@example.com',
            'tax_number' => '4334321098765',
            'country' => 'Canada',
            'city' => 'Calgary',
            'postal_code' => 'T2P 2M5',
            'address' => '789 17 Ave SW',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '123 Shipping Ave',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 18,
            'name' => 'Daniel Evans',
            'phone' => '0923456781',
            'email' => 'daniel.evans@example.com',
            'tax_number' => '69954321098007',
            'country' => 'United States',
            'city' => 'Miami',
            'postal_code' => '33132',
            'address' => '123 Biscayne Blvd',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '789 Shipping Ave',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 19,
            'name' => 'Avery Wilson',
            'phone' => '0432167890',
            'email' => 'avery.wilson@example.com',
            'tax_number' => '241098765432',
            'country' => 'United Kingdom',
            'city' => 'Edinburgh',
            'postal_code' => 'EH1 1RE',
            'address' => '456 Royal Mile',
            'billing_address' => '123 Billing Rd',
            'shipping_address' => '789 Shipping Rd',
            'status' => 'active',
            'isCustomer' => 1,
        ],
        [
            'id' => 20,
            'name' => 'Sofia Rodriguez',
            'phone' => '0709786421',
            'email' => 'sofia.rodriguez@example.com',
            'tax_number' => '243109876543',
            'country' => 'Australia',
            'city' => 'Sydney',
            'postal_code' => '2000',
            'address' => '123 George St',
            'billing_address' => '456 Billing Ave',
            'shipping_address' => '789 Shipping Ave',
            'status' => 'active',
            'isSupplier' => 1,
        ],
    ];

    public function run(): void
    {
        foreach ($this->parties as $p) {

            $party = new Party();

            $party->name = $p['name'];
            $party->phone = $p['phone'];
            $party->email = $p['email'];
            $party->tax_number = $p['tax_number'];
            $party->country = $p['country'];
            $party->city = $p['city'];
            $party->postal_code = $p['postal_code'];
            $party->address = $p['address'];
            $party->billing_address = $p['billing_address'];
            $party->shipping_address = $p['shipping_address'];
            $party->status = $p['status'];
            $party->isCustomer = $p['isCustomer'] ?? 0;
            $party->isSupplier = $p['isSupplier'] ?? 0;

            $party->save();
        }
    }
}
